name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - name: Install Go 1.18 beta version
        run: |
          go install golang.org/dl/go1.18beta1@latest
          go1.18beta1 download
          cp $(which go1.18beta1) $(which go)
          go version
      - name: Test
        run: |
          go1.18beta1 test
